on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  id-token: write

name: release

jobs:
  release_please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - id: release
        uses: googleapis/release-please-action@v4

  compress_sign_and_upload:
    needs: [release_please]
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: actions/setup
        uses: ./.github/actions/setup
      - name: Get release version and release package file name
        id: get_vars
        shell: bash
        run: |
          package_version=$(jq --raw-output '.version' package.json)
          echo "package_version=${package_version}" >> "$GITHUB_OUTPUT"
          echo "package_file=${{ inputs.npm_package_name }}-${package_version}.tgz" >> "$GITHUB_OUTPUT"
      - name: actions/compress_sign_and_upload
        uses: ./.github/actions/compress_sign_and_upload
        with:
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          aws_region_name: 'us-east-1'
          aws_secret_id: ${{ secrets.AWS_SECRET_ID }}
          npm_package_name: 'mongodb'
          dry_run: ${{ needs.release_please.outputs.release_created == '' }}
      # - run: npm publish --provenance
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Test 21
        shell: bash
        run: |
          mkdir files
          mv ${{ steps.get_vars.outputs.package_file }} files
          mv ${{ steps.get_vars.outputs.package_file }}.sig files

      - name: Generate authorized pub report
        uses: mongodb-labs/drivers-github-tools/authorized-pub@v2
        with:
          release_version: ${{ steps.get_version.outputs.package_version }}
          product_name: node-mongodb-native
          filenames: files/*
          token:  ${{ github.token }}

      - name: Test
        shell: bash
        run: |
          cat $S3_ASSETS/authorized-publication.txt

  generate_sarif_report:
    environment: release
    runs-on: ubuntu-latest
    needs: [release_please]
    permissions:
      # required for all workflows
      security-events: write
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up drivers-github-tools
        uses: mongodb-labs/drivers-github-tools/setup@v2
        with:
          aws_region_name: us-east-1
          aws_role_arn: ${{ secrets.aws_role_arn }}
          aws_secret_id: ${{ secrets.aws_secret_id }}

      - name: "Generate Sarif Report"
        uses: mongodb-labs/drivers-github-tools/code-scanning-export@v2
        with:
          ref: main
          output-file: sarif-report.json

      - name: Get release version and release package file name
        id: get_version
        shell: bash
        run: |
          package_version=$(jq --raw-output '.version' package.json)
          echo "package_version=${package_version}" >> "$GITHUB_OUTPUT"
      - name: actions/publish_asset_to_s3
        uses: mongodb-labs/drivers-github-tools/node/publish_asset_to_s3@v2
        with:
          version: ${{ steps.get_version.outputs.package_version }}
          product_name: node-mongodb-native
          file: sarif-report.json
          dry_run:  ${{ needs.release_please.outputs.release_created == '' }}


  upload_sbom_lite:
    environment: release
    runs-on: ubuntu-latest
    needs: [release_please]
    permissions:
      # required for all workflows
      security-events: write
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up drivers-github-tools
        uses: mongodb-labs/drivers-github-tools/setup@v2
        with:
          aws_region_name: us-east-1
          aws_role_arn: ${{ secrets.aws_role_arn }}
          aws_secret_id: ${{ secrets.aws_secret_id }}

      - name: Get release version and release package file name
        id: get_version
        shell: bash
        run: |
          package_version=$(jq --raw-output '.version' package.json)
          echo "package_version=${package_version}" >> "$GITHUB_OUTPUT"

      - name: actions/publish_asset_to_s3
        uses: mongodb-labs/drivers-github-tools/node/publish_asset_to_s3@v2
        with:
          version: ${{ steps.get_version.outputs.package_version }}
          product_name: node-mongodb-native
          file: sbom.json
          dry_run:  ${{ needs.release_please.outputs.release_created == '' }}

  generate_authorized_publishing_report:
    environment: release
    runs-on: ubuntu-latest
    needs: [release_please]
    permissions:
      # required for all workflows
      security-events: write
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up drivers-github-tools
        uses: mongodb-labs/drivers-github-tools/setup@v2
        with:
          aws_region_name: us-east-1
          aws_role_arn: ${{ secrets.aws_role_arn }}
          aws_secret_id: ${{ secrets.aws_secret_id }}

      - name: Get release version and release package file name
        id: get_version
        shell: bash
        run: |
          package_version=$(jq --raw-output '.version' package.json)
          echo "package_version=${package_version}" >> "$GITHUB_OUTPUT"

      - name: Generate authorized pub report
        uses: mongodb-labs/drivers-github-tools/authorized-pub@v2
        with:
          release_version: ${{ steps.get_version.outputs.package_version }}
          product_name: node-mongodb-native
          filenames: sbom.json
          token:  ${{ github.token }}

      - name: Test
        shell: bash
        run: |
          cat $S3_ASSETS/authorized-publication.txt
